using System.Text;
using System.Text.RegularExpressions;
using PocketFlow;

namespace CodebaseKnowledgeBuilder;

// ── Shared-store keys used across nodes ──────────────────────────────────────
//   "repo_url"          string?
//   "local_dir"         string?
//   "project_name"      string
//   "github_token"      string?
//   "output_dir"        string
//   "include_patterns"  List<string>
//   "exclude_patterns"  List<string>
//   "max_file_size"     long
//   "language"          string
//   "use_cache"         bool
//   "max_abstraction_num" int
//   "files"             List<(string path, string content)>
//   "abstractions"      List<Dict>  [{name, description, files:[int]}]
//   "relationships"     Dict        {summary, details:[{from,to,label}]}
//   "chapter_order"     List<int>
//   "chapters"          List<string>
//   "final_output_dir"  string


// Node 1 – FetchRepo
// Node 2 – IdentifyAbstractions
// Node 3 – AnalyzeRelationships
// Node 4 – OrderChapters
// Node 5 – WriteChapters  (BatchNode)
// Node 6 – CombineTutorial


public class CombineTutorial : Node
{
    protected override object? Prepare(object shared)
    {
        var store          = (Dictionary<string, object>)shared;
        var projectName    = (string)store["project_name"];
        var outputBaseDir  = SharedStore.Get(store, "output_dir", "output");
        var outputPath     = Path.Combine(outputBaseDir, projectName);
        var repoUrl        = SharedStore.Get<string?>(store, "repo_url", null);
        var relationships  = (Dictionary<string, object>)store["relationships"];
        var chapterOrder   = (List<int>)store["chapter_order"];
        var abstractions   = (List<Dictionary<string, object>>)store["abstractions"];
        var chaptersContent = (List<string>)store["chapters"];

        var details  = (List<Dictionary<string, object>>)relationships["details"];
        var summary  = relationships["summary"].ToString()!;

        // ── Mermaid diagram ─────────────────────────────────────────────────
        var mermaid = new StringBuilder("flowchart TD\n");
        for (int i = 0; i < abstractions.Count; i++)
        {
            var label = abstractions[i]["name"].ToString()!.Replace("\"", "");
            mermaid.AppendLine($"    A{i}[\"{label}\"]");
        }
        foreach (var rel in details)
        {
            var edge = rel["label"].ToString()!
                .Replace("\"", "").Replace("\n", " ");
            if (edge.Length > 30) edge = edge[..27] + "...";
            mermaid.AppendLine($"    A{rel["from"]} -- \"{edge}\" --> A{rel["to"]}");
        }

        // ── index.md ────────────────────────────────────────────────────────
        var index = new StringBuilder();
        index.AppendLine($"# Tutorial: {projectName}");
        index.AppendLine();
        index.AppendLine(summary);
        index.AppendLine();
        if (!string.IsNullOrEmpty(repoUrl))
        {
            index.AppendLine($"**Source Repository:** [{repoUrl}]({repoUrl})");
            index.AppendLine();
        }
        index.AppendLine("```mermaid");
        index.Append(mermaid);
        index.AppendLine("```");
        index.AppendLine();
        index.AppendLine("## Chapters");
        index.AppendLine();

        var chapterFiles = new List<(string filename, string content)>();
        for (int i = 0; i < chapterOrder.Count; i++)
        {
            int abstrIdx = chapterOrder[i];
            if (abstrIdx < 0 || abstrIdx >= abstractions.Count || i >= chaptersContent.Count) continue;

            var abstrName = abstractions[abstrIdx]["name"].ToString()!;
            var safeName  = Regex.Replace(abstrName, @"[^\w]", "_").ToLowerInvariant();
            var filename  = $"{i + 1:D2}_{safeName}.md";

            index.AppendLine($"{i + 1}. [{abstrName}]({filename})");

            var chapterContent = chaptersContent[i];
            if (!chapterContent.EndsWith("\n\n")) chapterContent += "\n\n";
            chapterContent += "---\n\nGenerated by [AI Codebase Knowledge Builder](https://github.com/The-Pocket/Tutorial-Codebase-Knowledge)";

            chapterFiles.Add((filename, chapterContent));
        }

        index.AppendLine();
        index.AppendLine("---");
        index.AppendLine();
        index.AppendLine("Generated by [AI Codebase Knowledge Builder](https://github.com/The-Pocket/Tutorial-Codebase-Knowledge)");

        return new Dictionary<string, object>
        {
            ["output_path"]   = outputPath,
            ["index_content"] = index.ToString(),
            ["chapter_files"] = chapterFiles,
        };
    }

    protected override object? Execute(object? prepRes)
    {
        var p            = (Dictionary<string, object>)prepRes!;
        var outputPath   = p["output_path"].ToString()!;
        var indexContent = p["index_content"].ToString()!;
        var chapterFiles = (List<(string filename, string content)>)p["chapter_files"];

        Console.WriteLine($"Combining tutorial into directory: {outputPath}");
        Directory.CreateDirectory(outputPath);

        var indexPath = Path.Combine(outputPath, "index.md");
        File.WriteAllText(indexPath, indexContent, System.Text.Encoding.UTF8);
        Console.WriteLine($"  - Wrote {indexPath}");

        foreach (var (filename, content) in chapterFiles)
        {
            var path = Path.Combine(outputPath, filename);
            File.WriteAllText(path, content, System.Text.Encoding.UTF8);
            Console.WriteLine($"  - Wrote {path}");
        }

        return outputPath;
    }

    protected override object? Post(object shared, object? prepRes, object? execRes)
    {
        ((Dictionary<string, object>)shared)["final_output_dir"] = execRes!;
        Console.WriteLine($"\nTutorial generation complete! Files are in: {execRes}");
        return null;
    }
}


